fieldLayouts:
  dae3a5c9-9d6c-4970-94ad-b75b08df7d05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf43cba7-e953-4a21-af75-17f404138c5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bab4509-fd86-4432-9349-b485ad305ff7 # like Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2aa09ad-53ee-4789-b00b-9b5feea2113e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5b7ca04-6137-41bf-ab70-95818c16f640 # story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ccbc357-69a3-470f-8d71-1596c5f605ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1afb17a2-eda3-40e4-bb7d-22cf4912fd95 # designAuthor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da55c5a5-7519-4c07-9958-86460d127422
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 296c3e3c-1354-4114-a2ba-86e0b4e9a8cd # design Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e57e0415-09a2-4080-af8e-6697ff8b4f65
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d3b04ba-04de-49c4-8d1b-a1036d3f1c9f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 098bf40a-4116-4672-b3b5-303b57a938cd # designs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
