fieldLayouts:
  8f53417c-abdb-45fb-9d53-2e2ee1c86f4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42cbc9db-4fc9-481d-974e-82e6c19c00bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b8d9845-0911-4773-9780-8d815de965e7 # workshop Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0a2101d-1980-4738-b174-2e654084e69d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a52452f8-8e9e-403e-b9aa-196220177fe4 # workshop Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13562c30-8e9e-4f3f-85df-9bdd06fd0bf3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0c3b8a5-3d7a-42a9-92cc-952786751245 # workshop Place
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c930c40-8c3c-4d31-86f3-cbb8e7f5d83d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70004032-9fbc-4b20-89b3-93b4647a2244 # workshop Attendees
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad4a3a5c-25c2-4465-bfe9-7764967b3320
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2324230-fafc-4fc1-a411-56e6a0fe8284
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 04609018-8bab-40f1-8455-a12c7fc950e5 # workshops
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
