fieldLayouts:
  225818fa-869d-472f-8ae4-0897f90bf7bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 283b1aae-b552-42a7-b0d0-d8d14d1838e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d96726f-8744-4b23-a6a5-49432ca9008e # workshop attendees
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5962be5-3971-4a2e-907c-16a4b803abea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7065b1b6-c2b2-4332-99e5-82d8f4f134c2 # workshop date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79305020-371f-4c99-adb1-3192f3e9cf52
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0dd6f1c-00ba-4436-bc05-84297ddd81de # workshop info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a50099a-9dce-4d33-83f9-9758e6e30552
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2fa98a8a-0943-4d4e-bdff-ae4f55e124c5 # workshop place
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d38dfa7a-c3b0-493b-b38a-127c4874bdf4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45b37f66-2cdc-451c-ac3b-8ec98031710c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a961ce14-1fcb-4209-92db-aa58b55893ba # workshops
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
