fieldLayouts:
  0220a7d2-383f-4c15-bcd4-4115762b84ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5f8561f-c0a1-4fd5-b894-57426bdd7fe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c43f9a04-8dfc-49b0-8677-12bd4f3bf04a # company adres
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11f0f170-9074-45dc-b06e-3251a90ce12c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ef94ed5-de0e-4808-a2f1-0a3a181f1f1a # company telephone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85edfa0c-c711-4fd2-9c36-40d986ebbf6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bdd34b2e-e240-4da6-a874-7c96ddcc2ac2 # request duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0a5b67e-cbad-44b4-aa7d-a4ca83d46292
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13306b01-989a-4391-a419-3b3ca7585bf4 # request Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1296af90-529b-4adf-9471-314ed5380d89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ae0f66c-bba8-4e6c-80bd-35c854fa0105 # request amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e6597e7-2334-4dda-bd89-475a2878a94b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17523622-6584-47f3-8426-d00a43c29d3d # company postcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1fb451a-5cc4-49c1-9d9c-ab674169c1fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3df38ff-3ab6-4601-9413-4c28908cbd3b # company mail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a880129-b66b-4664-9e0f-242191206a94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99dbc7e2-7d04-4ae9-ae0b-c6a737b851fb # company country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 544d6459-a64a-429e-96ba-38660578c26d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0550f92b-0ce2-4dfa-a525-8b47d30ef073
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 96175363-fb95-400e-81ca-6e4da39ee2ea # workshop Requests
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
