fieldLayouts:
  dae3a5c9-9d6c-4970-94ad-b75b08df7d05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf43cba7-e953-4a21-af75-17f404138c5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5b7ca04-6137-41bf-ab70-95818c16f640 # story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ccbc357-69a3-470f-8d71-1596c5f605ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9659a9aa-bb18-47b8-9f55-baed99d9bf6a # design
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b01d333-2d28-438a-a523-f577308f1649
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff55aa0c-39bb-4a7d-8901-87d77eda08fa # designAuthor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae5c6636-f132-40d6-b0aa-b046338739e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1366050-4ee0-4092-84e3-aab3987fe5b5 # designLinks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50532814-4f3b-467b-b220-38bb0f1da899
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d3b04ba-04de-49c4-8d1b-a1036d3f1c9f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 098bf40a-4116-4672-b3b5-303b57a938cd # designs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
