fieldLayouts:
  dae3a5c9-9d6c-4970-94ad-b75b08df7d05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf43cba7-e953-4a21-af75-17f404138c5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1bf328af-e246-4426-a514-b5c26a093a51 # designLinks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93d24c56-44da-485e-bb62-fb72f4083c6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c94a0b06-4385-4a7b-9494-af296fa8d782 # designAuthor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c839531-ef47-41a9-85d0-5225c0dead0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5b7ca04-6137-41bf-ab70-95818c16f640 # story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ccbc357-69a3-470f-8d71-1596c5f605ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d3b04ba-04de-49c4-8d1b-a1036d3f1c9f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 098bf40a-4116-4672-b3b5-303b57a938cd # designs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
