dateModified: 1687011570
email:
  fromEmail: minh.tri.ha@student.howest.be
  fromName: kultureX
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: uploads
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
meta:
  __names__:
    0d04ab93-2676-4032-b1f7-b03c2d16708a: Default # Default
    2b192ae7-68a4-4fcb-ac74-adee628d325d: Default # Default
    3c3816f3-e10f-4183-beae-7ab3f1fbc5e6: kultureX # kultureX
    3f687b4a-27f7-4066-bc76-55032f478541: workshopRequests # workshopRequests
    7b8d9845-0911-4773-9780-8d815de965e7: 'workshop Date' # workshop Date
    9d98e25c-74ac-4eaf-87bc-12801dc1c5ae: 'company Mail' # company Mail
    35c69e63-d07d-4933-ac1c-4bcfdee0632e: Common # Common
    47f6e445-399d-4b85-a62e-d616f9995a88: 'company Postcode' # company Postcode
    089dc85a-6074-4086-aca2-9ffb8cbf436a: 'request Date' # request Date
    098bf40a-4116-4672-b3b5-303b57a938cd: designs # designs
    609eb92c-57bd-4999-b1ef-94c97ed1a8f7: 'company Adres' # company Adres
    6364d90b-f6c2-4321-b8de-3905634d24af: 'workshop Requests' # workshop Requests
    346570d1-a361-4775-95ec-af7a9ee7592a: 'Public Schema' # Public Schema
    606668e5-cee9-4475-b7e0-5db2cd0c914f: tshirt-url # tshirt-url
    04609018-8bab-40f1-8455-a12c7fc950e5: workshops # workshops
    17688985-a8f9-4bcf-b2e8-131053d1f7d7: Senne # Senne
    25548588-7d50-453b-a303-b7f2f55ad45e: 'design Author' # design Author
    70004032-9fbc-4b20-89b3-93b4647a2244: 'workshop Attendees' # workshop Attendees
    97163395-0194-4622-850e-b48d3d65be82: Default # Default
    a0c3b8a5-3d7a-42a9-92cc-952786751245: 'workshop Place' # workshop Place
    a4bb78bd-ba2e-42df-82c6-c3498c1d4623: workshops # workshops
    a111acb4-f77e-4390-99c6-8453dbcbb8ab: 'request Duration' # request Duration
    a52452f8-8e9e-403e-b9aa-196220177fe4: 'workshop Info' # workshop Info
    b0fe49ca-cc76-423d-85b1-5114b12dad38: Dummy # Dummy
    bc830422-6413-440b-9ea9-7607f4129d76: tshirt # tshirt
    ca98a93c-411a-4bbc-9174-0e0b3a88fb5e: kultureX # kultureX
    d036df59-6e14-44aa-9ee5-26bd4f9b97ca: 'design uploads' # design uploads
    d5b7ca04-6137-41bf-ab70-95818c16f640: story # story
    d302d6aa-2069-43e5-b566-4dfe643783b4: 'company Name' # company Name
    d9971e81-3d61-46a9-bc6e-accdc289e797: 'like Amount' # like Amount
    de9bdcfb-66db-46aa-a23f-4ddcf0496932: 'company Telephone' # company Telephone
    ee9b1680-d7fc-47ea-a3ec-691fe2dc77e3: New # New
    f14c4821-885d-4000-b452-2c389b0fa89e: 'request Amount' # request Amount
    f879a9e3-ad1e-48f5-b1a3-22469eb0b849: 'company Country' # company Country
plugins:
  commerce:
    edition: lite
    enabled: true
    licenseKey: 6R4O7N9Y66GW5IQUXG523KMF
    schemaVersion: 4.2.3
    settings:
      activeCartDuration: 3600
      allowCheckoutWithoutPayment: false
      allowEmptyCartOnCheckout: false
      allowPartialPaymentOnCheckout: false
      autoSetCartShippingMethodOption: false
      autoSetNewCartAddresses: true
      autoSetPaymentSource: false
      cartVariable: cart
      defaultView: commerce/products
      dimensionUnits: mm
      emailSenderAddress: null
      emailSenderAddressPlaceholder: null
      emailSenderName: null
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: default
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showEditUserCommerceTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: g
  commerce-stripe:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: kultureX
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
