dateModified: 1686147686
elementSources:
  craft\commerce\elements\Product:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - type
        - postDate
        - expiryDate
        - defaultPrice
        - defaultSku
        - link
      type: native
    -
      heading: 'Product Types'
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'productType:17688985-a8f9-4bcf-b2e8-131053d1f7d7'
      tableAttributes:
        - postDate
        - expiryDate
        - defaultPrice
        - defaultSku
        - link
      type: native
email:
  fromEmail: minh.tri.ha@student.howest.be
  fromName: kultureX
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: images
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL
meta:
  __names__:
    0c51f0f3-64c9-42fa-86a4-e3f15df247f0: productImages # productImages
    1bf328af-e246-4426-a514-b5c26a093a51: designLinks # designLinks
    3c3816f3-e10f-4183-beae-7ab3f1fbc5e6: kultureX # kultureX
    03da7e37-1e7f-46be-8fae-c03eea6fab88: productImage # productImage
    35c69e63-d07d-4933-ac1c-4bcfdee0632e: Common # Common
    80dae144-c6c0-4b5c-a314-b3aff8fcef27: shirts # shirts
    098bf40a-4116-4672-b3b5-303b57a938cd: designs # designs
    904c00a1-afdb-4a06-a1b5-7f8d0ed258b6: Products # Products
    346570d1-a361-4775-95ec-af7a9ee7592a: 'Public Schema' # Public Schema
    97163395-0194-4622-850e-b48d3d65be82: Default # Default
    b0fe49ca-cc76-423d-85b1-5114b12dad38: Dummy # Dummy
    c94a0b06-4385-4a7b-9494-af296fa8d782: designAuthor # designAuthor
    ca98a93c-411a-4bbc-9174-0e0b3a88fb5e: kultureX # kultureX
    d5b7ca04-6137-41bf-ab70-95818c16f640: story # story
    ee9b1680-d7fc-47ea-a3ec-691fe2dc77e3: New # New
plugins:
  commerce:
    edition: lite
    enabled: true
    licenseKey: 6R4O7N9Y66GW5IQUXG523KMF
    schemaVersion: 4.2.3
    settings:
      activeCartDuration: 3600
      allowCheckoutWithoutPayment: false
      allowEmptyCartOnCheckout: false
      allowPartialPaymentOnCheckout: false
      autoSetCartShippingMethodOption: false
      autoSetNewCartAddresses: true
      autoSetPaymentSource: false
      cartVariable: cart
      defaultView: commerce/products
      dimensionUnits: mm
      emailSenderAddress: null
      emailSenderAddressPlaceholder: null
      emailSenderName: null
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: default
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showEditUserCommerceTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: g
  commerce-stripe:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: kultureX
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
