columnSuffix: zotpbmkr
contentColumnType: mediumtext
fieldGroup: 35c69e63-d07d-4933-ac1c-4bcfdee0632e # Common
handle: designLinks
instructions: null
name: designLinks
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: mediumtext
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
