columnSuffix: jclrncra
contentColumnType: integer(10)
fieldGroup: 35c69e63-d07d-4933-ac1c-4bcfdee0632e # Common
handle: likeAmount
instructions: null
name: 'like Amount'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
