columnSuffix: jztrzcxk
contentColumnType: smallint(2)
fieldGroup: bc48d364-fd3d-48d8-be8a-aca32725088f # workshops
handle: workshopAttendees
instructions: null
name: 'workshop attendees'
searchable: false
settings:
  decimals: 0
  defaultValue: 30
  max: 30
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
