columnSuffix: gsrrmrah
contentColumnType: text
fieldGroup: a4bb78bd-ba2e-42df-82c6-c3498c1d4623 # workshops
handle: workshopDate
instructions: null
name: 'workshop Date'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
