tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: c94a0b06-4385-4a7b-9494-af296fa8d782 # designAuthor
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: cb082774-ffd9-4681-b783-2d21021f159e
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: d5b7ca04-6137-41bf-ab70-95818c16f640 # story
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: fd554cda-e9b0-4b4d-bb88-bb6a5725459e
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 03da7e37-1e7f-46be-8fae-c03eea6fab88 # productImage
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f5fbac0d-4f9d-41ba-84e4-d06c9520ba63
        userCondition: null
        warning: null
        width: 100
    name: orders
    uid: b64d7998-de9d-456e-9bf6-70d100fb2d8f
    userCondition: null
